# fly.toml app configuration file generated for ponti-io on 2025-06-15T20:05:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ponti-io"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "covid_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "/data/covid.db"
