import { isLocal } from "@/utils/constant/env";

const showLogger = isLocal
	? true
	: process.env.NEXT_PUBLIC_SHOW_LOGGER === "true" ?? false;

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
	if (!showLogger) return;

	console.log(
		"%c ============== INFO LOG \n",
		"color: #22D3EE",
		`${typeof window !== "undefined" && window?.location.pathname}\n`,
		`=== ${comment ?? ""}\n`,
		object,
	);
}
