name: deploy-fly

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows: ["docker-publish-api"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Get image tag
        id: image
        run: |
          # Get the latest image tag from the registry
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to Fly.io
        run: flyctl deploy --image ${{ steps.image.outputs.image }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 