name: deploy-prod-railway

on:
  workflow_run:
    workflows: ["docker-publish-api"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy API to Railway
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_PONTI_IO }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1 # Use a more recent version
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 